name: Vite React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # ✅ Verify that the build succeeded and dist folder is not empty
    - name: Verify build output
      run: |
        if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
          echo "❌ Build directory is empty!"
          exit 1
        else
          echo "✅ Build completed and dist folder contains files."
        fi
